In [29]:
import numpy as np
arr=np.array([3,5,34,5,34,53,5])
print(type(arr))

<class 'numpy.ndarray'>


In [30]:
num=303
num2=num
while num>0:
    l_digit=num%10
    rnum=rnum*10+l_digit
    num//=10


if(rnum==num2):
    print(f"{num} is palindrome")
else:
    print(f"{num} is not palindrome")

NameError: name 'rnum' is not defined

In [ ]:
a=10
a=a/10
print(a)

1


In [ ]:
num=303
num2=num
rnum=0
while num>0:
    l_digit=num%10
    rnum=rnum*10+l_digit
    num//=10


if(rnum==num2):
    print(f"{num2} is palindrome")
else:
    print(f"{num2} is not palindrome")

303 is palindrome


In [ ]:
class Animal:
    def speak(self):
        return "meu"
    
obj=Animal()
obj.speak()

'meu'

In [ ]:
class A:
    def myfunction(self,num):
         num2=num
         num=str(num)
         num=num[::-1]
         if(num==str(num2)):
             print("palindrome")
         else:
              print("not palindrome")

obj=A()
num=101
z=303
obj.myfunction(num)
obj.myfunction(z)

palindrome


In [ ]:
n=4
f_n=1
for i in range(1,n+1):
    f_n*=i
print(f_n)

24


In [ ]:
num=5
for i in range(1,num+1):
    for j in range(i):
        print("*",end =" ")
    print()        

* 
* * 
* * * 
* * * * 
* * * * * 


#Banking System

Create a banking system with the following requirements:

A base class Account with attributes account_number, holder_name, and balance.

Methods: deposit(), withdraw(), and get_balance().

Two subclasses:

SavingsAccount (with interest calculation).

CurrentAccount (with overdraft limit).

Implement polymorphism where withdraw() behaves differently for both accounts.

Add a Bank class to manage multiple accounts and transactions.

In [ ]:
class Account:
    def __init__(self,account_number,holder_name,balance):
        self.accout_number=account_number
        self.holder_name=holder_name
        self.balance=balance

    def deposite(self,amount):
        self.balance+=amount
        print(f"After the deposite amount balance is= {self.balance}")

    def withdraw(self,amount):
        if amount>self.balance:
            self.balance-=amount
            print("After the withdrawing the balance is= {self.balance}")
    
    def get_balance(self):
        return self.balance

class Saving_Account(Account):
    def __init__(self,account_number,holder_name,balance):
        super().__init__(account_number,holder_name,balance)

    def interst(self,interests):
        self.balance +=(interests/100)*self.balance
        print(f"After the interest your balance is= {self.balance}")
    

class Current_Account(Account):
    def __init__(self,account_number,holder_name,balance):
        super().__init__(account_number,holder_name,balance)





obj1=Saving_Account(1234,"Pratik",5000)
obj1.interst(10)


After the interest your balance is= 5500.0


In [32]:
import numpy as np
arr=np.array([4,4,3,53,5])
print(arr[1:])


[ 4  3 53  5]


In [42]:
arr=np.array([[1, 0, 4,4,2],
               [4, 3, 6,3,4]])
#print(arr.ndim)
print(arr[1, 0:3])

[4 3 6]


In [54]:
arr2 = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr2[1, 1:4])


[7 8 9]


In [55]:
print(arr2.shape)

(2, 5)


In [56]:
print(arr2.size)

10


In [89]:
np.random.randint(10,size=(2,3))

array([[0, 5, 6],
       [7, 3, 2]])

In [57]:
np.zeros((2,3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)


<U6


In [52]:
import numpy as np
str=np.array(["pratik","jaswant","om","tanya","chaitany"])
print(str.dtype)

<U8


In [53]:
print(str.shape)

(5,)


In [103]:
arr=np.array([[[2,3,4,5],[2,4,3,4]]])
print(arr.ndim)
print(arr.shape)

3
(1, 2, 4)


In [105]:
a=np.array({2,34,3,24})
print(a)

{24, 2, 3, 34}


In [114]:
b=np.array([[[1,2,3,4,5],[6,7,8,9,10],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10],[6,7,8,9,10]]])
print(b)
print(b.ndim)
print(b.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [ 6  7  8  9 10]]]
3
(2, 3, 5)


In [116]:
x4d=[b,b]
print(x4d)

[array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 6,  7,  8,  9, 10]]]), array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 6,  7,  8,  9, 10]]])]


In [122]:
ar1=np.array([[1,2,3,4],[5,6,7,8]])
print(ar1[1,2]+ar1[0,2])

10


In [130]:
my_arr=np.random.choice([1,2,3,4], p=[0.3,0.3,0.3,0.1], size=10)
print(my_arr)

[2 4 3 3 3 4 1 1 2 1]


In [134]:
my_arr=np.random.randint(100,size=30)
my_arr

array([34, 47, 66, 39, 71, 37, 87, 25, 83,  7, 95, 60, 66, 26, 69, 61, 37,
       56, 29, 64, 93, 40, 43, 14, 19, 29, 16, 61, 83, 55])

In [135]:
my_arr=np.random.randint(100,size=(2,2))
my_arr

array([[28, 45],
       [86, 48]])

In [141]:
arr3=np.array((1,4,3,6,2))
print(np.sort(arr3))

[1 2 3 4 6]


In [158]:
from numpy import random
random.shuffle(arr3)
print(arr3)

[4 3 2 1 6]


In [155]:
arr3=np.array((1,4,3,6,2))
print(random.permutation(arr3))


[1 4 3 2 6]


In [220]:
a=10
b=10
print(a is b)
#c=a**b
#d=a//b
#print(d)

True


In [190]:
str="balojibaba"
#print(str[1])
for i in "balojibaba dhorale":
    print(i,end="")

balojibaba dhorale

In [191]:
if str in "a":
    print("present")

In [ ]:
str="pratik Nanasaheb shinde"
str2="Om Nanasaheb Shinde"
#a=(str2.split())[2]
#print(a)
#c=str+str2
print(f"{str} {str2}")

pratik shinde om critical thinking in a main road


In [203]:
print(str.replace("pratik","om"))

om shinde


In [209]:
str="pratik Nanasaheb shinde"
if "bsd" in str:
    print("present")
else:
    print("not present")

not present


In [243]:
my_list=[11,12,13,14,15,16,17,18,27,26]
#print(my_list)
#print(my_list[-3:])
my_list[0:7]=[1,2,3,4,5,6,7]
print(my_list)

[1, 2, 3, 4, 5, 6, 7, 18, 27, 26]


In [228]:
for i in range(0,len(my_list)):
    print(my_list[i],end=" ")

11 12 13 14 15 16 17 18 27 26 

In [307]:
my_list={"a","b","c","d"}
my2_list=[11,22,13,14,15,16,17,18,27,26]
#my2_list.extend(my_list)
#print(my2_list)
print(my2_list)

[11, 22, 13, 14, 15, 16, 17, 18, 27, 26]


In [308]:
#my2_list.remove(11)
print(my2_list)

[11, 22, 13, 14, 15, 16, 17, 18, 27, 26]


In [309]:
print(my2_list)
new_list=[i for i in my2_list if 20<i ]
print(new_list)

[11, 22, 13, 14, 15, 16, 17, 18, 27, 26]
[22, 27, 26]


In [310]:
print(my_list)
new=[i for i in my_list if 'a' in i]
print(new)

{'d', 'a', 'b', 'c'}
['a']


In [312]:
my2_list.sort(reverse=True)
print(my2_list)

[27, 26, 22, 18, 17, 16, 15, 14, 13, 11]


In [314]:
my22=my2_list
print(my22)

[27, 26, 22, 18, 17, 16, 15, 14, 13, 11]


In [ ]:
class Product:
    def __init__(self,id,name, price,stock):
        self.id=id
        self.name=name
        self.price=price
        self.stock=stock

    '''def check_stock(self, quantity):
        if(self.stock>=quantity):
             print("Given Product avaible")
        else:
            print("sorry product is  not avaliable")'''
    

    def purchace_product(self,purches):
        if(self.stock>=purches):
            print("Successful puches")
        else:
            print("Stock is empty")
        self.stock-=self.stock
    


class Customer():
    def __init__(self,id,name,cart):
        self.id=id
        self.name=name
        self.cart=cart





obj1=Product(1,"Pratik",12000,10)
obj1.purchace_product(10)
obj1.purchace_product(1)



    


    


Successful puches
Stock is empty


In [349]:
import numpy as np
from numpy import random
a=random.randint(10)
print(a)

6
